title: Hungertek
author: Bhanu Prakash G
email: bhanuprakash@kustommade.com
description: > # this means to ignore newlines until "baseurl:"
  Technology at finger tips.

# social links
twitter_username: your-twitter-handle
github_username:  bhanukustom

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-hacker
